version: '3.8'

services:
  # MCP Registry Service
  mcp-registry:
    image: mcp/registry:latest
    ports:
      - "8081:8081"
    volumes:
      - mcp-registry-data:/var/lib/mcp/registry
    environment:
      - MCP_REGISTRY_LOG_LEVEL=info
      - MCP_REGISTRY_AUTH_TOKEN=${MCP_AUTH_TOKEN:-default-dev-token}
    networks:
      - mcp-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/v1/health"]
      interval: 10s
      timeout: 5s
      retries: 5

  # MCP Router Service
  mcp-router:
    image: mcp/router:latest
    ports:
      - "8080:8080"
    volumes:
      - ./mcp-config:/etc/mcp
    environment:
      - MCP_ROUTER_LOG_LEVEL=info
      - MCP_REGISTRY_URL=http://mcp-registry:8081
      - MCP_ROUTER_AUTH_TOKEN=${MCP_AUTH_TOKEN:-default-dev-token}
    networks:
      - mcp-network
    depends_on:
      mcp-registry:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/v1/health"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Revit MCP Tool Service
  revit-mcp-tool:
    build:
      context: ..
      dockerfile: docker/Dockerfile.mcp-revit
    environment:
      - MCP_TOOL_LOG_LEVEL=debug
      - MCP_REGISTRY_URL=http://mcp-registry:8081
      - MCP_TOOL_ID=revit
      - MCP_TOOL_AUTH_TOKEN=${MCP_AUTH_TOKEN:-default-dev-token}
      - REVIT_HOST=${REVIT_HOST:-host.docker.internal}
      - REVIT_PORT=${REVIT_PORT:-5000}
    volumes:
      - ../RevitMcpServer:/app/revit-server
      - revit-data:/app/revit-data
    networks:
      - mcp-network
    depends_on:
      mcp-router:
        condition: service_healthy

  # Vector Database for RAG
  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant-data:/qdrant/storage
    networks:
      - mcp-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:6333/health"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Graph Database for Knowledge
  neo4j:
    image: neo4j:5-community
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=neo4j/revitgraph
      - NEO4J_dbms_memory_pagecache_size=1G
      - NEO4J_dbms.memory.heap.initial_size=1G
      - NEO4J_dbms_memory_heap_max__size=2G
    volumes:
      - neo4j-data:/data
      - neo4j-logs:/logs
    networks:
      - mcp-network

  # Demo UI for MCP Testing
  mcp-demo-ui:
    image: mcp/demo-ui:latest
    ports:
      - "3000:3000"
    environment:
      - MCP_ROUTER_URL=http://mcp-router:8080
      - MCP_AUTH_TOKEN=${MCP_AUTH_TOKEN:-default-dev-token}
    networks:
      - mcp-network
    depends_on:
      mcp-router:
        condition: service_healthy

networks:
  mcp-network:
    driver: bridge

volumes:
  mcp-registry-data:
  revit-data:
  qdrant-data:
  neo4j-data:
  neo4j-logs:
